title: Conway's Game of Life
baseURL: ""
theme:
  github.com/CaiJimmy/hugo-theme-stack
  #github.com/adityatelange/hugo-PaperMod
  #github.com/Club404/theme
  #github.com/theNewDynamic/gohugo-theme-ananke
  #github.com/panr/hugo-theme-terminal


menu:
  main:
    - identifier: rules
      name: Game Rules
      url: /about/rules/
      weight: 10
    - identifier: simple-shapes
      name: Shapes and Patterns
      url: /about/simple-shapes/
      weight: 11
    - identifier: signal-generators
      name: Signal Generators
      url: /about/signal-generators/
      weight: 12
    - identifier: turing-complete
      name: Advanced Use Cases
      url: /about/turing-complete/
      weight: 13

params:
  # Define the default author
  author: Johnathan Lodder
  authorimage: https://avatars.githubusercontent.com/u/141126234?s=200&v=4

  # Params required by terminal
  fullWidthTheme: false
  centerTheme: true
  
# Add the shortcodes as a hugo module
module:
  imports:
    - path: github.com/planet-lodder/shortcodes-hugo

