# ------------------------------------------------------------
# This project is powered by: https://taskfile.dev
# ------------------------------------------------------------
version: 3
env: # <-- Project Configuration (required ENV vars)
  PUBLISH_REPO: git@github.com:planet-lodder/planet-lodder.github.io.git
  PUBLISH_TEMP: ./temp/web
tasks:
  init:
    desc: Install and required dependencies
    sources:
      - config.yaml
      - go.mod
      - go.sum
    generates:
      - resources/
    cmds:
      - "[ -f go.mod ] || go mod init main"
      - hugo mod get -u

  build:
    desc: Build the website and save the output in `public/`
    deps: [init]
    cmds:
      - yarn build
      - hugo --minify

  start:
    desc: Run the Hugo server locally
    deps: [init]
    cmds:
      - hugo server -s .

  serve:
    desc: Run the Python server locally
    deps: [init]
    cmds:
      - |-
        cd examples/python
        open http://localhost:9999/game-of-life
        python3 ./main.py --dev


  publish: 
    desc: Publish the latest website from `public/`
    deps: [build]
    cmds:
      - |-
        printf "Release (%s): " $(git tag | tail -n 1)
        read tag
        git tag $tag 
        git push origin --tags        
        jq '.version="'$tag'"' package.json > package.json.tmp
        mv package.json.tmp package.json
      #- npm login
      - npm publish --access=public

  # Clean out all and any untracked data (incl. git changed files)
  clean: git clean -fdX
